<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net8.0</TargetFrameworks>
        <NoWarn>$(NoWarn);CS1591</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="IKVM" Version="8.15.0" />
        <PackageReference Include="IKVM.Java.Extensions" Version="8.15.0" />
        <PackageReference Include="IKVM.Maven.Sdk" Version="1.12.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
        <PackageReference Include="coverlet.collector" Version="10.0.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="xunit" Version="2.9.3" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <MavenReference Include="org.apache.calcite:calcite-core" Version="1.42.0" />
        <MavenReference Include="org.jooq:joou-java-6" Version="0.9.5" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Apache.Calcite.Data.Common\Apache.Calcite.Data.Common.csproj" />
    </ItemGroup>

</Project>
