<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
        <NoWarn>$(NoWarn);CS1591</NoWarn>
    </PropertyGroup>

    <PropertyGroup>
        <CalciteLocalMavenRepo>$(MSBuildThisFileDirectory)ext\maven-repo</CalciteLocalMavenRepo>
        <MavenAdditionalRepositories>$(MavenAdditionalRepositories);calcite-local=file:///$([MSBuild]::NormalizePath('$(CalciteLocalMavenRepo)').Replace('\','/'));</MavenAdditionalRepositories>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="IKVM" Version="8.15.0" />
        <PackageReference Include="IKVM.Java.Extensions" Version="8.15.0" />
        <PackageReference Include="IKVM.Maven.Sdk" Version="1.11.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
        <PackageReference Include="xunit" Version="2.9.3" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <MavenReference Include="org.apache.calcite:calcite-core" Version="1.42.0-SNAPSHOT" />
        <MavenReference Include="org.apache.calcite:calcite-server" Version="1.42.0-SNAPSHOT" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Apache.Calcite.Data\Apache.Calcite.Data.csproj" />
    </ItemGroup>

</Project>
