using org.apache.calcite.linq4j.tree;
using org.apache.calcite.runtime;

namespace Apache.Calcite.Linq4j
{

    /// <summary>
    /// Compiles a Calcite-generated <see cref="ClassDeclaration"/> into a runnable CLR
    /// <see cref="Bindable"/> without using Janino or any other JVM-hosted compiler.
    /// </summary>
    /// <remarks>
    /// Implement this abstract class and supply an instance to
    /// <c>CalciteConnection.PrepareFactory</c> (via <see cref="ClrCalcitePrepare"/>) to replace
    /// Calcite's default Janino-based compilation path with a CLR expression-tree pipeline.
    /// </remarks>
    public abstract class ClrBindableCompiler
    {

        /// <summary>
        /// Compiles the supplied <paramref name="classDeclaration"/> into a <see cref="Bindable"/>
        /// that can be executed directly by the Calcite runtime.
        /// </summary>
        /// <param name="classDeclaration">
        /// The linq4j <see cref="ClassDeclaration"/> generated by Calcite for the current query.
        /// </param>
        /// <param name="classBody">
        /// The Janino source text that Calcite would normally compile, provided for diagnostic
        /// purposes. The CLR implementation can ignore this string entirely.
        /// </param>
        /// <param name="fieldCount">
        /// Number of field declarations present in <paramref name="classDeclaration"/>. Provided
        /// as a convenience; the caller can also count them from the declaration itself.
        /// </param>
        /// <returns>A <see cref="Bindable"/> ready to be executed against a <c>DataContext</c>.</returns>
        public abstract Bindable Compile(ClassDeclaration classDeclaration, string classBody, int fieldCount);

    }

}
